server:
  port: 8763
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /zerg/*
      serviceId: provider
    api-b:
      path: /ribbon/*
      serviceid: ribbon
    api-c:
      path: /feign/*
      serviceid: feign